import { icons, COLORS } from '../constants';

const data = [
  {
    id: 1,
    name: 'Education',
    icon: icons.education,
    color: COLORS.yellow,
    expenses: [
      {
        id: 1,
        title: 'Tuition Fee',
        description: 'Tuition Fee',
        location: 'Byprogrammers tuition center',
        total: 100.0,
        status: 'P',
      },
      {
        id: 2,
        title: 'Arduino',
        description: 'Hardward',
        location: 'Byprogrammers tuition center',
        total: 30.0,
        status: 'P',
      },
      {
        id: 3,
        title: 'Javascript Book',
        description: 'Javascript Book',
        location: 'Byprogrammers book store',
        total: 20.0,
        status: 'P',
      },
      {
        id: 4,
        title: 'PHP Book',
        description: 'PHP Book',
        location: 'Byprogrammers book store',
        total: 20.0,
        status: 'C',
      },
    ],
  },
  {
    id: 2,
    name: 'Nutrition',
    icon: icons.food,
    color: COLORS.lightblue,
    expenses: [
      {
        id: 5,
        title: 'Vitamin',
        description: 'Vitamin',
        location: 'Byprogrammers pharmacy',
        total: 25.0,
        status: 'P',
      },
      {
        id: 6,
        title: 'Protein Powder',
        description: 'Protein Powder',
        location: 'Byprogrammers pharmacy',
        total: 50.0,
        status: 'C',
      },
    ],
  },
  {
    id: 3,
    name: 'Child',
    icon: icons.playtime,
    color: COLORS.darkgreen,
    expenses: [
      {
        id: 7,
        title: 'Toys',
        description: 'Toys',
        location: 'Byprogrammers toy center',
        total: 25.0,
        status: 'C',
      },
      {
        id: 8,
        title: 'Baby Car Seat',
        description: 'Baby Car Seat',
        location: 'Byprogrammers toy center',
        total: 100.0,
        status: 'P',
      },
      {
        id: 9,
        title: 'Pampers',
        description: 'Pampers',
        location: 'Byprogrammers supermarket',
        total: 100.0,
        status: 'P',
      },
      {
        id: 10,
        title: 'Baby T-shirt',
        description: 'Baby T-shirt',
        location: 'Byprogrammers fashion store',
        total: 20.0,
        status: 'P',
      },
    ],
  },
  {
    id: 4,
    name: 'Beauty & Care',
    icon: icons.healthcare,
    color: COLORS.peach,
    expenses: [
      {
        id: 11,
        title: 'Skincare Product',
        description: 'Skincare',
        location: 'Byprogrammers pharmacy',
        total: 10.0,
        status: 'P',
      },
      {
        id: 12,
        title: 'Lotion',
        description: 'Lotion',
        location: 'Byprogrammers pharmacy',
        total: 50.0,
        status: 'C',
      },
      {
        id: 13,
        title: 'Face Mask',
        description: 'Face Mask',
        location: 'Byprogrammers pharmacy',
        total: 50.0,
        status: 'P',
      },
      {
        id: 14,
        title: 'Sunscreen cream',
        description: 'Sunscreen cream',
        location: 'Byprogrammers Pharmacy',
        total: 50.0,
        status: 'P',
      },
    ],
  },
  {
    id: 5,
    name: 'Sport',
    icon: icons.sport,
    color: COLORS.purple,
    expenses: [
      {
        id: 15,
        title: 'Gym Membership',
        description: 'Gym Membership',
        location: 'Byprogrammers Gym',
        total: 45.0,
        status: 'P',
      },
      {
        id: 16,
        title: 'Glove',
        description: 'Gym Equipment',
        location: 'Byprogrammers Gym',
        total: 15.0,
        status: 'C',
      },
    ],
  },
  {
    id: 6,
    name: 'Clothing',
    icon: icons.clothes,
    color: COLORS.red,
    expenses: [
      {
        id: 17,
        title: 'Tshirt',
        description: 'Tshirt Pink',
        location: 'Byprogrammers Mall',
        total: 20.0,
        status: 'P',
      },
      {
        id: 18,
        title: 'Jean',
        description: 'Blue Jean',
        location: 'Byprogrammers Mall',
        total: 50.0,
        status: 'C',
      },
    ],
  },
];

export default data;
